# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  enabled: true
  host: 192.168.1.105
  port: 3001

development:
  <<: *default

test:
  <<: *default
  enabled: false

production:
  <<: *default
  enabled: false
